
language: python

matrix:
  include:

# travis does not support Python 3.1 and there is a problem with pytest and Python 3.2 on travis

    - dist: trusty
      python: "3.2"

    - dist: trusty
      python: "3.3"

    - python: "3.4"

    - python: "3.5"

    - python: "3.6"

    - dist: xenial
      python: "3.7"

    - python: "pypy3.5"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install -v .

before_script:

  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]]; then pip install pytest==3.0; fi

  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.2" ]]; then pip install pytest==2.9; fi

script:
  - cd tests
  - py.test

