#dist:
#  - trusty  # for python 3.2 and 3.3
#  - xenial  # for python 3.7
#language: python
#python:
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7"
#  - "pypy3.5"

matrix:
  include:
    - dist: trusty
      python: "3.2"

    - dist: trusty
      python: "3.3"

    - python: "3.4"

    - python: "3.5"

    - python: "3.6"

    - dist: xenial
      python: "3.7"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install -v .

script:
  - cd tests
  - py.test

