
language: python

matrix:
  include:

# travis does not support Python 3.1 anymore

    - dist: trusty
      python: "3.2"

    - dist: trusty
      python: "3.3"

    - python: "3.4"

    - python: "3.5"

    - python: "3.6"

    - dist: xenial
      python: "3.7"

    - python: "pypy3.5"

install:
  - pip install -r requirements.txt
  - pip install -v .

script:
  - python ./setup.py test
