dist: xenial  # for python 3.7
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install -v .

script:
  - cd tests
  - py.test

