
language: python

matrix:
  include:

    - dist: trusty
      python: "3.1"

    - dist: trusty
      python: "3.2"

    - dist: trusty
      python: "3.3"

    - python: "3.4"

    - python: "3.5"

    - python: "3.6"

    - dist: xenial
      python: "3.7"

    - pypy: "3.5"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install -v .

before_script:

  - if [[ "$TOXENV" == "py3.3" ]]; then pip install pytest==2.9; fi

script:
  - cd tests
  - py.test

